spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置HikariCP数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #等待连接池分配连接的最大时长（毫秒），超过这个时长没有可用的连接则发生SQLException，默认30秒
      connection-timeout: 30000
      #最小连接数
      minimum-idle: 5
      #最大连接数
      maximum-pool-size: 15
      #自动提交
      auto-commit: true
      #一个连接idle状态的最大时长（毫秒），超时则被回收，默认10分钟
      idle-timeout: 600000
      #连接池名字
      pool-name: DatebookHikariCP
      #一个连接的生命时长（毫秒），超时且没有被使用则释放，默认30分钟1800000ms
      max-lifetime: 28740000
      connection-test-query: SELECT 1
###security###
jwt:
  secret: swpu-uchain
  expiration: 1296000
server:
  tomcat:
    uri-encoding: utf-8
    connection-timeout: 18000000
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 15001
  connect-timeout: 15001
  thumb-image:             #缩略图生成参数
    width: 80
    height: 80
  tracker-list[0]: 218.244.151.128:22122